MedicalInformationShare/MedicalInformationShare/Controllers/MedicineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MedicalInformationShare.App_Start;
using MedicalInformationShare.Models;
using MedicalInformationShare.Context;
using EntityState = System.Data.EntityState;


namespace MedicalInformationShare.Controllers
{
     [AuthorizationFilter]
    public class MedicineController : Controller
    {
        private MedicalContext db = new MedicalContext();
        private int HospitalId;
        public MedicineController()
        {
            if (System.Web.HttpContext.Current.Session["HospitalId"] != null)
            {
                HospitalId = (int) System.Web.HttpContext.Current.Session["HospitalId"];
            }
            
        }
        // GET: /Medicine/
        public ActionResult MedicineIndex()
        {
            return View(db.Medicines.Where(r=>r.HospitalId==HospitalId).ToList());
        }

       

        // GET: /Medicine/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Medicine/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Name,Measurement,Company")] Medicine medicine)
        {
            if (ModelState.IsValid)
            {
                medicine.HospitalId = HospitalId;
                db.Medicines.Add(medicine);
                db.SaveChanges();
                return RedirectToAction("MedicineIndex");
            }

            return View(medicine);
        }

        // GET: /Medicine/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }

        // POST: /Medicine/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,Measurement,Company")] Medicine medicine)
        {
            
            if (ModelState.IsValid)
            {
                medicine.HospitalId = HospitalId;
                db.Entry(medicine).State = (System.Data.Entity.EntityState) EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("MedicineIndex");
            }
            return View(medicine);
        }

        

        // POST: /Medicine/Delete/5
        
        public ActionResult Delete(int id)
        {
            Medicine medicine = db.Medicines.Find(id);
            db.Medicines.Remove(medicine);
            db.SaveChanges();
            return RedirectToAction("MedicineIndex");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MedicalInformationShare/MedicalInformationShare/Controllers/PrimaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MedicalInformationShare.App_Start;
using MedicalInformationShare.Context;

namespace MedicalInformationShare.Controllers
{
    [AuthorizationFilter]
   
    public class PrimaryController : Controller
    {
        
        //
        // GET: /Primary/
        MedicalContext db=new MedicalContext();
        private int HospitalId;

        public PrimaryController()
        {
            if (System.Web.HttpContext.Current.Session["HospitalId"] != null)
            {
                HospitalId = (int)System.Web.HttpContext.Current.Session["HospitalId"];
            }
        }
        
        public ActionResult Index()
        {
            ViewBag.Blood = db.Bloods.Where(r => r.HospitalId == HospitalId).ToList();
            ViewBag.Medicine = db.Medicines.Where(r => r.HospitalId == HospitalId).ToList();
            return View();
        }

        public ActionResult SearchInventory(int id)
        {

            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
	}
}

MedicalInformationShare/MedicalInformationShare/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.Design;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MedicalInformationShare.App_Start;
using MedicalInformationShare.Context;
using MedicalInformationShare.Models;

namespace MedicalInformationShare.Controllers
{
    [AuthorizationFilter]
    public class SearchController : Controller
    {
        private MedicalContext db = new MedicalContext();
        //
        // GET: /Search/
        public ActionResult SearchBlood()
        {
            var data = from b in db.Bloods
                join h in db.Hospitals on b.HospitalId equals h.Id
                select new
                {
                    bId = b.Id,
                    bGroup=b.BloodGroup,
                    bBag = b.AvailableBag,
                    hName=h.Name,
                    hAddress=h.Address,
                    hPhone=h.Phone,
                    hEmail=h.Email
                };
            List<HospitalElementView> hospitalElementViews = new List<HospitalElementView>();
            foreach (var d in data)
            {
                HospitalElementView h = new HospitalElementView();
                h.Blood.Id = d.bId;
                h.Blood.BloodGroup = d.bGroup;
                h.Blood.AvailableBag = d.bBag;
                h.Hospital.Name = d.hName;
                h.Hospital.Address = d.hAddress;
                h.Hospital.Phone = d.hPhone;
                h.Hospital.Email = d.hEmail;
                hospitalElementViews.Add(h);
            }

            return View(hospitalElementViews);
            
        }
        public ActionResult SearchMedicine()
        {
            var data = from m in db.Medicines
                       join h in db.Hospitals on m.HospitalId equals h.Id
                       select new
                       {
                           mId = m.Id,
                           mName = m.Name,
                           mCompany = m.Company,
                           mUnit=m.Measurement,
                           hName = h.Name,
                           hAddress = h.Address,
                           hPhone = h.Phone,
                           hEmail = h.Email
                       };
            List<HospitalElementView> hospitalElementViews = new List<HospitalElementView>();
            foreach (var d in data)
            {
                HospitalElementView h = new HospitalElementView();
                h.Medicine.Id = d.mId;
                h.Medicine.Name = d.mName;
                h.Medicine.Company = d.mCompany;
                h.Medicine.Measurement = d.mUnit;
                h.Hospital.Name = d.hName;
                h.Hospital.Address = d.hAddress;
                h.Hospital.Phone = d.hPhone;
                h.Hospital.Email = d.hEmail;
                hospitalElementViews.Add(h);
            }

            return View(hospitalElementViews);

        }

        public ActionResult SearchDoctor()
        {
            var data = from m in db.Doctors
                       join h in db.Hospitals on m.HospitalId equals h.Id
                       select new
                       {
                           mId = m.Id,
                           mName = m.Name,
                           mDesignation = m.Designation,
                           mImage = m.Image,
                           hName = h.Name,
                           hAddress = h.Address,
                           hPhone = h.Phone,
                           hEmail = h.Email
                       };
            List<HospitalElementView> hospitalElementViews = new List<HospitalElementView>();
            foreach (var d in data)
            {
                HospitalElementView h = new HospitalElementView();
                h.Doctor.Id = d.mId;
                h.Doctor.Name = d.mName;
                h.Doctor.Designation = d.mDesignation;
                h.Doctor.Image = d.mImage;
                h.Hospital.Name = d.hName;
                h.Hospital.Address = d.hAddress;
                h.Hospital.Phone = d.hPhone;
                h.Hospital.Email = d.hEmail;
                hospitalElementViews.Add(h);
            }

            return View(hospitalElementViews);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
	}
}

MedicalInformationShare/MedicalInformationShare/Views/Primary/Index.cshtml
@using MedicalInformationShare.Models

@{
    ViewBag.Title = "Index";
}


<div class="row scrchk">
    <div class="col-md-3">
        <div class="left-side">
            <h5 style="margin-top: 10px;"><i class="fas fa-search icnmar"></i>Search Inventory</h5>
            <div class="list-group ovrchk">
                <a class="list-gp" href="@Url.Action("SearchDoctor", "Search")">Doctor</a>
                <a class="list-gp" href="@Url.Action("SearchBlood", "Search")">Blood Bank</a>
                <a class="list-gp" href="@Url.Action("SearchMedicine", "Search")">Medicine</a>
                <a class="list-gp" href="@Url.Action("SearchInventory", "Search")">OT instrument</a>
                <a class="list-gp" href="@Url.Action("SearchInventory", "Search")">Emergency instruemnt</a>
                <a class="list-gp" href="@Url.Action("SearchInventory", "Search")">Available bed</a>
            </div>
        </div>
        
    </div>
    <div class="col-md-6">
        <div class="left-side">
            <h5 style="margin-top: 10px;"><i class="fas fa-hand-holding-water icnmar"></i>Blood Bank</h5>
            <div class="dvtable">
                <table class="table table-bordered table-striped table-hover" id="bloodbank" style="width: 31em;">
                    <thead>
                    <tr>
                        <th>Serial No</th>
                        <th>Blood Group</th>
                        <th>AvailableBag</th>
                    </tr>
                    </thead>
                    <tbody id="tableBody">
                    @{
                        int ii = 1;
                        foreach (Blood b in ViewBag.Blood)
                        {
                            <tr>
                                <td>@ii</td>
                                <td>@b.BloodGroup</td>
                                <td>@b.AvailableBag</td>
                            </tr>
                            ii++;
                        }

                    }
                    </tbody>

                </table>
            </div>

            <hr/>
            <h5 style="margin-top: 10px;"><i class="fas fa-capsules icnmar"></i>Medicine Store</h5>
            <div class="dvtable">
                <table class="table table-bordered table-striped table-hover" id="medicine" style="width: 31em;">
                    <thead>
                    <tr>
                        <th>Serial No</th>
                        <th>Name</th>
                        <th>Power</th>
                        <th>Company</th>

                    </tr>
                    </thead>
                    <tbody id="tableBody">
                    @{
                        int i = 1;
                        foreach (Medicine m in ViewBag.Medicine)
                        {
                            <tr>
                                <td>@i</td>
                                <td>@m.Name</td>
                                <td>@m.Measurement</td>
                                <td>@m.Company</td>
                            </tr>
                            i++;
                        }

                    }
                    </tbody>

                </table>
            </div>
            <hr/>
            </div>
        </div>
    <div class="col-md-3">
        <div class="left-side">
            <h5 style="margin-top: 10px;"><i class="fas fa-dolly-flatbed icnmar"></i>Add Assets</h5>
            <div class="list-group ovrchk">
                <a class="list-gp" href="@Url.Action("Doctor", "Doctor")">Doctor</a>
                <a class="list-gp" href="@Url.Action("Blood", "Blood")">Blood Bank</a>
                <a class="list-gp" href="@Url.Action("MedicineIndex", "Medicine")">Medicine</a>
                <a class="list-gp" href="@Url.Action("SearchInventory", "Primary", new {id = 3})">OT instrument</a>
                <a class="list-gp" href="@Url.Action("SearchInventory", "Primary", new {id = 4})">Emergency instruemnt</a>
                <a class="list-gp" href="@Url.Action("SearchInventory", "Primary", new {id = 5})">Available bed</a>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/aos.js"></script>

    <script>
        AOS.init();
        $(document).ready(function () {
            $('#bloodbank').DataTable();
            $('#medicine').DataTable();

        });

    </script>

}